_target_: src.models.contrastive_module.ContrastiveModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.hf_nets.HFT5Encoder
  cfg_name: 't5-base'
  embedding_path: null

